"""Shared pandera-polars column factories for CLIF 2.1.0 table schemas (U3).

Every per-table schema (in ``schemas/<table>.py``, generated by
``scripts/gen_schemas.py``) is assembled from these factories, so the three
machine-checkable CLIF conformance rules live in exactly one place:

- **R5** — ``*_category`` values are exact, case-sensitive members of the 2.1.0
  mCIDE list (``category`` -> ``Check.isin``).
- **R7** — datetimes are tz-aware UTC (``utc_datetime`` -> ``DateTime(time_zone="UTC")``).
- **R9** — numerics fall inside the consortium outlier bounds
  (``bounded_float`` -> ``Check.in_range``).

Permissive-by-default policy: generated columns are ``required=False,
nullable=True`` so a schema never rejects a valid frame merely for omitting an
optional CLIF column, while still enforcing dtype/category/bounds/tz wherever a
column *is* present. Identifier columns are the exception — ``id_column`` is
``required=True, nullable=False`` because referential integrity (R8) depends on
them. A table unit tightens ``required`` on the columns it actually emits.
"""

from __future__ import annotations

import pandera.polars as pa
import polars as pl
from pandera.engines.polars_engine import DateTime

from clifforge.reference import bounds, categories, loader

#: Tz-aware UTC datetime dtype — a naive (tz-less) datetime column fails validation.
UTC_DATETIME = DateTime(time_zone="UTC")

#: THE ID-TYPE RULE, validation side. These three analyst-facing join keys are
#: emitted as integers (see ``generate._common.enforce_numeric_ids``, which imports
#: this tuple) and so must NOT be dtype-pinned to ``str`` like other ``*_id``
#: columns. :func:`build_column` and ``scripts/gen_schemas.py`` both branch on this,
#: which is what keeps the committed schema modules identical to the runtime builder.
NUMERIC_ID_COLUMNS = ("patient_id", "hospitalization_id", "hospitalization_joined_id")

#: The referential backbone (R8): the only id columns that are required *and*
#: non-nullable. Every canonical 2.1 table that has these declares them required.
#:
#: Other ``*_id`` columns are deliberately NOT required, because canonically they
#: are not: clifpy's 2.1 schemas mark ``device_id``, ``med_order_id``,
#: ``hospitalization_joined_id``, ``billing_provider_id``, ``performing_provider_id``
#: and ``microbiology_susceptibility.organism_id`` optional. Treating every
#: ``*_id`` as mandatory (the old ``endswith("_id")`` heuristic) rejected frames
#: CLIF considers valid, and would have made a no-growth culture — which has no
#: organism to identify — impossible to represent.
REQUIRED_ID_COLUMNS = ("patient_id", "hospitalization_id")

#: CLIF dictionary data types treated as floating point.
_FLOAT_DTYPES = {"DOUBLE", "FLOAT", "NUMERIC"}
#: CLIF dictionary data types treated as integer.
_INT_DTYPES = {"INT", "INTEGER", "BIGINT"}
#: CLIF dictionary data types treated as boolean.
_BOOL_DTYPES = {"BOOLEAN", "BOOL"}


def id_column(*, required: bool = False, nullable: bool = True) -> pa.Column:
    """String identifier column (``device_id``, ``provider_id``, ``organism_id``, ...).

    Optional and nullable by default, matching canonical 2.1: these ids are how a
    row *may* link to another table, not a guarantee that it does.
    """
    return pa.Column(str, nullable=nullable, required=required)


def numeric_id_column(*, required: bool = True, nullable: bool = False) -> pa.Column:
    """Required, non-nullable **integer** identifier — ``patient_id`` /
    ``hospitalization_id`` / ``hospitalization_joined_id`` — the hardcoded id-type
    rule (see ``generate._common.enforce_numeric_ids``).

    The generator emits these as ``Int64`` (the hardcoded id-type rule in
    ``generate._common.enforce_numeric_ids``, applied to every table) so they load as
    numbers — no leading zeros, no string coercion — in Python, R, and Stata. The
    schema keeps the referential backbone (present + non-null, R8) without pinning the
    dtype, so the always-integer output and any string-built test frame both validate;
    other id columns (``device_id``, ``provider_id``, …) stay strings."""
    return pa.Column(nullable=False, required=True)


def string(*, required: bool = False, nullable: bool = True) -> pa.Column:
    return pa.Column(str, required=required, nullable=nullable)


def integer(*, required: bool = False, nullable: bool = True) -> pa.Column:
    return pa.Column(int, required=required, nullable=nullable)


def boolean(*, required: bool = False, nullable: bool = True) -> pa.Column:
    return pa.Column(bool, required=required, nullable=nullable)


def plain_float(*, required: bool = False, nullable: bool = True) -> pa.Column:
    return pa.Column(float, required=required, nullable=nullable)


def utc_datetime(*, required: bool = False, nullable: bool = True) -> pa.Column:
    """Tz-aware UTC datetime column (R7); naive datetimes fail validation."""
    # pandera accepts an engine dtype instance here at runtime; its stub types
    # the first arg to the narrower dtype union, so this is a stub gap, not a bug.
    return pa.Column(UTC_DATETIME, required=required, nullable=nullable)  # type: ignore[arg-type]


def date(*, required: bool = False, nullable: bool = True) -> pa.Column:
    """Calendar-date column (no time, no zone).

    The canonical DDL types ``patient.birth_date`` as ``DATE``, distinct from the
    ``DATETIME`` columns R7 requires to be tz-aware UTC — a birth date has no
    meaningful instant, so it must not be forced into a UTC timestamp.
    """
    return pa.Column(pl.Date, required=required, nullable=nullable)


def category(table: str, field: str, *, required: bool = False, nullable: bool = True) -> pa.Column:
    """String column constrained to the exact mCIDE permissible values (R5).

    ``field`` is the mCIDE field key (e.g. ``"sex_category"``). Raises via the
    loader if the table/field has no vendored category list — a schema can never
    silently drop the membership check.
    """
    return pa.Column(
        str,
        checks=pa.Check.isin(categories(table, field)),
        required=required,
        nullable=nullable,
    )


def bounded_float(
    table: str, key: str, *, required: bool = False, nullable: bool = True
) -> pa.Column:
    """Float column constrained to the consortium outlier bounds (R9)."""
    lower, upper = bounds(table, key)
    return pa.Column(
        float,
        checks=pa.Check.in_range(lower, upper),
        required=required,
        nullable=nullable,
    )


def _category_field(table: str, name: str) -> str | None:
    """Return the mCIDE field key for column ``name`` in ``table``, or ``None``.

    Handles the dictionary/mCIDE naming skew where a data column is ``hospital_type``
    but its mCIDE field key is ``hospital_type_category``.
    """
    try:
        available = set(loader.mcide_fields(table))
    except loader.ReferenceDataError:
        return None
    if name in available:
        return name
    if f"{name}_category" in available:
        return f"{name}_category"
    return None


def build_column(table: str, name: str, dtype: str) -> pa.Column:
    """Map one dictionary ``(name, dtype)`` to the strictest applicable column type.

    Precedence: mCIDE category (isin) > datetime (UTC) > id > numeric (with bounds
    where available) > boolean > string fallback. ``UNKNOWN`` dtypes (columns the
    dictionary leaves untyped) default to string.
    """
    dt = dtype.upper()

    field = _category_field(table, name)
    if field is not None:
        return category(table, field)

    if dt == "DATETIME":
        return utc_datetime()

    if dt == "DATE":
        return date()

    if name in NUMERIC_ID_COLUMNS:
        backbone = name in REQUIRED_ID_COLUMNS
        return numeric_id_column(required=backbone, nullable=not backbone)

    if name.endswith("_id"):
        return id_column()

    if dt in _FLOAT_DTYPES:
        try:
            return bounded_float(table, name)
        except loader.ReferenceDataError:
            return plain_float()

    if dt in _INT_DTYPES:
        return integer()

    if dt in _BOOL_DTYPES:
        return boolean()

    return string()


def schema_from_dictionary(table: str) -> pa.DataFrameSchema:
    """Build a complete pandera schema for ``table`` from vendored dictionary + mCIDE.

    Returns a permissive-but-enforcing ``DataFrameSchema`` (``strict=False`` so extra
    ``*_name`` / source columns are allowed). Table units refine the returned schema
    with clinical-coupling checks via ``.update_column()`` / ``.add_columns()``.
    """
    columns = {
        col["name"]: build_column(table, col["name"], col["dtype"])
        for col in loader.table_columns(table)
    }
    return pa.DataFrameSchema(columns, strict=False, coerce=False, name=table)
