"""AUTO-GENERATED by scripts/gen_schemas.py from the CLIF 2.1.0 data dictionary.

Do not hand-edit the generated column list; regenerate with
``uv run python scripts/gen_schemas.py``. A table unit MAY append clinical-coupling
refinements below SCHEMA via .update_column()/.add_columns() (see U3 / R15).

Table: clinical_trial (untiered)
"""

from __future__ import annotations

import pandera.polars as pa

from clifforge.schemas import base

SCHEMA: pa.DataFrameSchema = pa.DataFrameSchema(
    {
        "hospitalization_id": base.numeric_id_column(),
        "trial_id": base.id_column(),
        "trial_name": base.string(),
        "arm_id": base.id_column(),
        "consent_dttm": base.utc_datetime(),
        "randomized_dttm": base.utc_datetime(),
        "withdrawal_dttm": base.utc_datetime(),
    },
    strict=False,
    coerce=False,
    name="clinical_trial",
)
