"""AUTO-GENERATED by scripts/gen_schemas.py from the CLIF 2.1.0 data dictionary.

Do not hand-edit the generated column list; regenerate with
``uv run python scripts/gen_schemas.py``. A table unit MAY append clinical-coupling
refinements below SCHEMA via .update_column()/.add_columns() (see U3 / R15).

Table: code_status (concept)
"""

from __future__ import annotations

import pandera.polars as pa

from clifforge.schemas import base

SCHEMA: pa.DataFrameSchema = pa.DataFrameSchema(
    {
        "patient_id": base.numeric_id_column(),
        "start_dttm": base.utc_datetime(),
        "code_status_name": base.string(),
        "code_status_category": base.category("code_status", "code_status_category"),
    },
    strict=False,
    coerce=False,
    name="code_status",
)
