"""AUTO-GENERATED by scripts/gen_schemas.py from the CLIF 2.1.0 data dictionary.

Do not hand-edit the generated column list; regenerate with
``uv run python scripts/gen_schemas.py``. A table unit MAY append clinical-coupling
refinements below SCHEMA via .update_column()/.add_columns() (see U3 / R15).

Table: crrt_therapy (concept)
"""

from __future__ import annotations

import pandera.polars as pa

from clifforge.schemas import base

SCHEMA: pa.DataFrameSchema = pa.DataFrameSchema(
    {
        "hospitalization_id": base.numeric_id_column(),
        "device_id": base.id_column(),
        "recorded_dttm": base.utc_datetime(),
        "crrt_mode_name": base.string(),
        "crrt_mode_category": base.category("crrt_therapy", "crrt_mode_category"),
        "dialysis_machine_name": base.string(),
        "blood_flow_rate": base.bounded_float("crrt_therapy", "blood_flow_rate"),
        "pre_filter_replacement_fluid_rate": base.bounded_float(
            "crrt_therapy", "pre_filter_replacement_fluid_rate"
        ),
        "post_filter_replacement_fluid_rate": base.bounded_float(
            "crrt_therapy", "post_filter_replacement_fluid_rate"
        ),
        "dialysate_flow_rate": base.bounded_float("crrt_therapy", "dialysate_flow_rate"),
        "ultrafiltration_out": base.plain_float(),
    },
    strict=False,
    coerce=False,
    name="crrt_therapy",
)
