"""AUTO-GENERATED by scripts/gen_schemas.py from the CLIF 2.1.0 data dictionary.

Do not hand-edit the generated column list; regenerate with
``uv run python scripts/gen_schemas.py``. A table unit MAY append clinical-coupling
refinements below SCHEMA via .update_column()/.add_columns() (see U3 / R15).

Table: ecmo_mcs (concept)
"""

from __future__ import annotations

import pandera.polars as pa

from clifforge.schemas import base

SCHEMA: pa.DataFrameSchema = pa.DataFrameSchema(
    {
        "hospitalization_id": base.numeric_id_column(),
        "recorded_dttm": base.utc_datetime(),
        "device_name": base.string(),
        "device_category": base.string(),
        "mcs_group": base.string(),
        "ecmo_configuration_category": base.string(),
        "control_parameter_name": base.string(),
        "control_parameter_category": base.string(),
        "control_parameter_value": base.plain_float(),
        "flow": base.plain_float(),
        "sweep_set": base.plain_float(),
        "fdO2_set": base.plain_float(),
    },
    strict=False,
    coerce=False,
    name="ecmo_mcs",
)
