"""AUTO-GENERATED by scripts/gen_schemas.py from the CLIF 2.1.0 data dictionary.

Do not hand-edit the generated column list; regenerate with
``uv run python scripts/gen_schemas.py``. A table unit MAY append clinical-coupling
refinements below SCHEMA via .update_column()/.add_columns() (see U3 / R15).

Table: hospitalization (beta)
"""

from __future__ import annotations

import pandera.polars as pa

from clifforge.schemas import base

SCHEMA: pa.DataFrameSchema = pa.DataFrameSchema(
    {
        "patient_id": base.numeric_id_column(),
        "hospitalization_id": base.numeric_id_column(),
        "hospitalization_joined_id": base.numeric_id_column(required=False, nullable=True),
        "admission_dttm": base.utc_datetime(),
        "discharge_dttm": base.utc_datetime(),
        "age_at_admission": base.integer(),
        "admission_type_name": base.string(),
        "admission_type_category": base.category("hospitalization", "admission_type_category"),
        "discharge_name": base.string(),
        "discharge_category": base.category("hospitalization", "discharge_category"),
        "zipcode_nine_digit": base.string(),
        "zipcode_five_digit": base.string(),
        "census_block_code": base.string(),
        "census_block_group_code": base.string(),
        "census_tract": base.string(),
        "state_code": base.string(),
        "county_code": base.string(),
        "fips_version": base.string(),
    },
    strict=False,
    coerce=False,
    name="hospitalization",
)
