"""AUTO-GENERATED by scripts/gen_schemas.py from the CLIF 2.1.0 data dictionary.

Do not hand-edit the generated column list; regenerate with
``uv run python scripts/gen_schemas.py``. A table unit MAY append clinical-coupling
refinements below SCHEMA via .update_column()/.add_columns() (see U3 / R15).

Table: hospital_diagnosis (concept)
"""

from __future__ import annotations

import pandera.polars as pa

from clifforge.schemas import base

SCHEMA: pa.DataFrameSchema = pa.DataFrameSchema(
    {
        "hospitalization_id": base.numeric_id_column(),
        "diagnosis_code": base.string(),
        "diagnosis_code_format": base.string(),
        "diagnosis_primary": base.integer(),
        "poa_present": base.integer(),
    },
    strict=False,
    coerce=False,
    name="hospital_diagnosis",
)
