"""AUTO-GENERATED by scripts/gen_schemas.py from the CLIF 2.1.0 data dictionary.

Do not hand-edit the generated column list; regenerate with
``uv run python scripts/gen_schemas.py``. A table unit MAY append clinical-coupling
refinements below SCHEMA via .update_column()/.add_columns() (see U3 / R15).

Table: medication_admin_intermittent (concept)
"""

from __future__ import annotations

import pandera.polars as pa

from clifforge.schemas import base

SCHEMA: pa.DataFrameSchema = pa.DataFrameSchema(
    {
        "hospitalization_id": base.numeric_id_column(),
        "med_order_id": base.id_column(),
        "admin_dttm": base.utc_datetime(),
        "med_name": base.string(),
        "med_category": base.category("medication_admin_intermittent", "med_category"),
        "med_group": base.string(),
        "med_route_name": base.string(),
        "med_route_category": base.category("medication_admin_intermittent", "med_route_category"),
        "med_dose": base.plain_float(),
        "med_dose_unit": base.string(),
        "mar_action_name": base.string(),
        "mar_action_category": base.category(
            "medication_admin_intermittent", "mar_action_category"
        ),
        "mar_action_group": base.string(),
    },
    strict=False,
    coerce=False,
    name="medication_admin_intermittent",
)
