"""AUTO-GENERATED by scripts/gen_schemas.py from the CLIF 2.1.0 data dictionary.

Do not hand-edit the generated column list; regenerate with
``uv run python scripts/gen_schemas.py``. A table unit MAY append clinical-coupling
refinements below SCHEMA via .update_column()/.add_columns() (see U3 / R15).

Table: patient (beta)
"""

from __future__ import annotations

import pandera.polars as pa

from clifforge.schemas import base

SCHEMA: pa.DataFrameSchema = pa.DataFrameSchema(
    {
        "patient_id": base.numeric_id_column(),
        "race_name": base.string(),
        "race_category": base.category("patient", "race_category"),
        "ethnicity_name": base.string(),
        "ethnicity_category": base.category("patient", "ethnicity_category"),
        "sex_name": base.string(),
        "sex_category": base.category("patient", "sex_category"),
        "birth_date": base.date(),
        "death_dttm": base.utc_datetime(),
        "language_name": base.string(),
        "language_category": base.category("patient", "language_category"),
    },
    strict=False,
    coerce=False,
    name="patient",
)
