"""AUTO-GENERATED by scripts/gen_schemas.py from the CLIF 2.1.0 data dictionary.

Do not hand-edit the generated column list; regenerate with
``uv run python scripts/gen_schemas.py``. A table unit MAY append clinical-coupling
refinements below SCHEMA via .update_column()/.add_columns() (see U3 / R15).

Table: patient_diagnosis (untiered)
"""

from __future__ import annotations

import pandera.polars as pa

from clifforge.schemas import base

SCHEMA: pa.DataFrameSchema = pa.DataFrameSchema(
    {
        "patient_id": base.numeric_id_column(),
        "hospitalization_id": base.numeric_id_column(),
        "diagnosis_code": base.string(),
        "diagnosis_code_format": base.string(),
        "source_type": base.string(),
        "start_dttm": base.utc_datetime(),
        "end_dttm": base.utc_datetime(),
    },
    strict=False,
    coerce=False,
    name="patient_diagnosis",
)
