"""One-time fit driver: real CLIF dataset -> aggregate parameter pack (U5).

This is the **only** module in ``clifforge`` that opens a real-data path
(KTD-1). Everything downstream — generation, conformance, evaluation — consumes
the parameter pack, never the source records. The driver:

1. Discovers and lazily scans the real CLIF tables under ``--real-dir``.
2. Computes a **seeded, patient-disjoint** train/holdout split. Only the split
   *spec* (seed, fraction, method, counts) is written to the pack manifest —
   never patient identifiers (that would trip the leakage gate). U22's TSTR
   evaluation recomputes the identical holdout set from the seed.
3. Fits the training partition only: demographic/encounter marginals, the
   semi-Markov organ-support spine (transitions + sojourns), per-state AR1
   physiology, the lab co-measurement copula, and infusion hazards — every
   cell routed through the n>=20 gate (R2).
4. Runs a **field-level source audit**: for each fitted table, labels every
   CLIF 2.1.0 column ``modeled`` (a parameter was fit for it), ``source_present``
   (the real source carries it but U5 fit nothing — passthrough/prior downstream),
   or ``prior`` (absent from the real source, new-in-2.1.0 — filled by the
   prior-driven stage, U20). A column with no fitted marginal is never labeled
   "fitted" (plan §272).
5. Assembles the pack, runs the value-level leakage scan, and writes it. No
   row-level real record ever leaves this function.

Usage::

    python -m clifforge.fit.run_fit --real-dir /path/to/CLIF --out data/param_packs/clif

The real path is a CLI argument and is never committed to the repo.
"""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path

import polars as pl

from clifforge.fit import estimators, spine_state
from clifforge.fit.cell_gate import SuppressionRecord
from clifforge.fit.param_pack import ParamPack, scan_for_leakage
from clifforge.fit.spine_state import SpineStateConfig
from clifforge.provenance import DEFAULT_CITATION
from clifforge.reference import loader

# Demographic / encounter categorical fields fit as marginals.
_PATIENT_CATEGORICALS = ("sex_category", "race_category", "ethnicity_category")
_HOSPITALIZATION_CATEGORICALS = ("admission_type_category", "discharge_category")

# Columns for which each table actually estimates a distribution/parameter, keyed
# by table. Drives the ``modeled`` label in the field-source audit — only these
# are backed by a fitted marginal; every other source column is generated by
# passthrough/prior downstream and must never be mislabeled "fitted" (plan §272).
# For the long value tables, the modeled columns are the category selector and
# the value being modeled; ``med_dose`` is deliberately absent because the
# infusion estimator models on/off timing per ``med_category``, not dose.
_MODELED_COLUMNS: dict[str, frozenset[str]] = {
    "patient": frozenset(_PATIENT_CATEGORICALS),
    "hospitalization": frozenset((*_HOSPITALIZATION_CATEGORICALS, "age_at_admission")),
    "vitals": frozenset({"vital_category", "vital_value"}),
    "labs": frozenset({"lab_category", "lab_value_numeric"}),
    "medication_admin_continuous": frozenset({"med_category"}),
    "code_status": frozenset({"code_status_category"}),
    "adt": frozenset({"location_category", "location_type", "hospital_type"}),
    "respiratory_support": frozenset(
        {
            "device_category",
            "mode_category",
            "fio2_set",
            "peep_set",
            "tidal_volume_set",
            "resp_rate_set",
        }
    ),
    "medication_admin_intermittent": frozenset({"med_category"}),
    "microbiology_culture": frozenset(
        {"fluid_category", "method_category", "organism_category", "organism_group"}
    ),
    "crrt_therapy": frozenset(
        {
            "crrt_mode_category",
            "blood_flow_rate",
            "dialysate_flow_rate",
            "ultrafiltration_out",
        }
    ),
    "ecmo_mcs": frozenset({"device_category", "mcs_group", "flow", "sweep", "fdO2"}),
    "patient_assessments": frozenset({"assessment_category"}),
    "position": frozenset({"position_category"}),
    "hospital_diagnosis": frozenset({"diagnosis_code", "diagnosis_primary"}),
    "patient_procedures": frozenset({"procedure_code"}),
    "invasive_hemodynamics": frozenset({"measure_category", "measure_value"}),
    "transfusion": frozenset({"component_name", "volume_transfused"}),
    "key_icu_orders": frozenset({"order_category"}),
    "therapy_details": frozenset({"therapy_element_category"}),
    "provider": frozenset({"provider_role_category"}),
    "microbiology_nonculture": frozenset(
        {"fluid_category", "organism_category", "result_category"}
    ),
    "intake_output": frozenset({"fluid_name", "amount", "in_out_flag"}),
    "clinical_trial": frozenset({"trial_id"}),
    "place_based_index": frozenset({"index_name", "index_value"}),
}

# Vitals fit with per-state AR1 (static anthropometrics excluded).
_AR1_VITALS = (
    "heart_rate",
    "sbp",
    "dbp",
    "map",
    "spo2",
    "respiratory_rate",
    "temp_c",
)

# CLIF table -> datetime column used to place a row on the interval grid.
_GRID_DTTM = {
    "vitals": "recorded_dttm",
    "labs": "lab_result_dttm",
    "medication_admin_continuous": "admin_dttm",
}

#: Support level at or above which a hospitalization counts as ICU-exposed, used to
#: condition lab-presence fitting on the ICU population (mirrors the generator's
#: ``generate._common.ICU_MIN_SUPPORT_LEVEL``; kept local to preserve fit→generate layering).
_ICU_MIN_SUPPORT_LEVEL = 2

#: ADT ``location_category`` value marking an ICU location (mCIDE).
_ICU_LOCATION_CATEGORY = "icu"


def _icu_cohort(adt: pl.LazyFrame | None) -> set[str]:
    """Clinically-defined ICU cohort: hospitalizations with an ICU ADT location.

    This is the population the synthetic dataset represents, so it is the correct
    denominator for per-stay lab presence. Returns an empty set when ADT or its
    ``location_category`` column is unavailable, signalling the caller to fall
    back to the latent support-level cohort.
    """
    if adt is None:
        return set()
    if "location_category" not in set(adt.collect_schema().names()):
        return set()
    return set(
        adt.filter(pl.col("location_category") == _ICU_LOCATION_CATEGORY)
        .select("hospitalization_id")
        .unique()
        .collect()
        .to_series()
        .to_list()
    )


# --------------------------------------------------------------------------- #
# Real-data discovery (KTD-1: confined to this module)
# --------------------------------------------------------------------------- #
def _find_table(real_dir: Path, table: str) -> Path | None:
    """Locate a CLIF table file under ``real_dir``.

    Accepts the maturity-tagged forge layout (``clif_<table>_2.1_<maturity>``),
    the untagged consortium layout (``clif_<table>``), and a bare ``<table>``
    stem — real site extracts use the untagged form; forge-generated packs use
    the tagged one.
    """
    from clifforge.generate.filenames import table_parquet_stem

    stems = (table_parquet_stem(table), f"clif_{table}", table)
    for stem in stems:
        for ext in (".parquet", ".csv"):
            candidate = real_dir / f"{stem}{ext}"
            if candidate.exists():
                return candidate
    return None


def _scan(path: Path) -> pl.LazyFrame:
    if path.suffix == ".parquet":
        return pl.scan_parquet(path)
    return pl.scan_csv(path, try_parse_dates=True, infer_schema_length=10000)


def _load_tables(real_dir: Path) -> dict[str, pl.LazyFrame]:
    """Lazily scan every CLIF table present under ``real_dir``."""
    tables: dict[str, pl.LazyFrame] = {}
    for table in loader.dictionary_tables():
        path = _find_table(real_dir, table)
        if path is not None:
            tables[table] = _scan(path)
    return tables


# --------------------------------------------------------------------------- #
# Seeded, patient-disjoint split (spec-only in the manifest — no identifiers)
# --------------------------------------------------------------------------- #
def _holdout_mask(patient_id: str, seed: int, holdout_fraction: float) -> bool:
    """Deterministic per-patient holdout membership from a stable hash.

    ``sha1(seed:patient_id) mod 10_000 < fraction*10_000``. Reproducible from
    the seed alone, so U22 recomputes the identical split without the pack ever
    storing an identifier.
    """
    digest = hashlib.sha1(f"{seed}:{patient_id}".encode()).hexdigest()
    bucket = int(digest[:8], 16) % 10_000
    return bucket < int(holdout_fraction * 10_000)


def _split_patients(
    patient_ids: list[str], seed: int, holdout_fraction: float
) -> tuple[set[str], dict[str, object]]:
    """Return the training patient-id set and an identifier-free split spec."""
    train = {pid for pid in patient_ids if not _holdout_mask(pid, seed, holdout_fraction)}
    holdout_n = len(patient_ids) - len(train)
    spec = {
        "method": "sha1_mod_10000",
        "seed": seed,
        "holdout_fraction": holdout_fraction,
        "train_n_patients": len(train),
        "holdout_n_patients": holdout_n,
    }
    return train, spec


# --------------------------------------------------------------------------- #
# Gridding helpers
# --------------------------------------------------------------------------- #
def _grid_value_table(
    lf: pl.LazyFrame,
    admits: pl.LazyFrame,
    *,
    dttm_col: str,
    category_col: str,
    value_col: str,
    config: SpineStateConfig,
) -> pl.DataFrame:
    """Resample a long value table to (hospitalization, interval, category)-mean."""
    delta_hours = (pl.col(dttm_col) - pl.col("_admit")).dt.total_seconds() / 3600.0
    interval = (delta_hours / config.grid_step_hours).floor().cast(pl.Int64)
    return (
        lf.join(admits, on="hospitalization_id", how="inner")
        .with_columns(interval.alias("interval_idx"))
        .filter((pl.col("interval_idx") >= 0) & (pl.col("interval_idx") < config.horizon_intervals))
        .group_by("hospitalization_id", "interval_idx", category_col)
        .agg(pl.col(value_col).mean().alias("value"))
        .collect()
    )


# --------------------------------------------------------------------------- #
# Field-level source audit
# --------------------------------------------------------------------------- #
def _field_sources(
    table: str, source_columns: set[str], modeled_columns: frozenset[str]
) -> list[dict[str, str]]:
    """Per CLIF column, the provenance of its downstream-generated values.

    Three states, because "present in the real source" and "backed by a fitted
    parameter" are different facts and conflating them overclaims fidelity — the
    plan (§272) is explicit that a column with no fitted marginal is *never*
    labeled ``fitted``:

    * ``modeled`` — U5 estimated a distribution/parameter for this column from
      the real training data (it is one of ``modeled_columns``); downstream
      generation samples it from that fit.
    * ``source_present`` — the real source carries the column but U5 fit no
      parameter for it (e.g. ``birth_date``, ``zipcode_nine_digit``,
      ``census_tract``); generation reproduces it by passthrough/pattern or a
      prior, **not** from a fitted marginal.
    * ``prior`` — the column is absent from the real source (typically new in
      CLIF 2.1.0); the prior-driven stage (U20) must synthesize it.

    Returned as a list of ``{"column", "source"}`` records rather than a
    ``{column: source}`` dict on purpose: identifier column names
    (``patient_id``, ``hospitalization_id``) are legitimate audit *content*
    here, but the pack leakage scanner forbids them as *keys*. As string values
    under a neutral ``"column"`` key they carry the same information without
    tripping the key-based guard.
    """
    records: list[dict[str, str]] = []
    for col in loader.table_columns(table):
        name = col["name"]
        if name in modeled_columns:
            source = "modeled"
        elif name in source_columns:
            source = "source_present"
        else:
            source = "prior"
        records.append({"column": name, "source": source})
    return records


def _source_columns(lf: pl.LazyFrame) -> set[str]:
    return set(lf.collect_schema().names())


def _record_table(
    name: str,
    df: pl.DataFrame,
    params: dict[str, object],
    records: list[SuppressionRecord],
    table_blocks: dict[str, dict[str, object]],
    field_audit: dict[str, list[dict[str, str]]],
    all_records: list[SuppressionRecord],
    source_columns: set[str],
) -> None:
    """Attach a fitted prior-table block when any params survived the gate."""
    if not params:
        return
    all_records.extend(records)
    table_blocks[name] = {
        "n_records": df.height,
        "fitted": True,
        "params": params,
    }
    modeled = _MODELED_COLUMNS.get(name, frozenset())
    field_audit[name] = _field_sources(name, source_columns, modeled)


def _record_with_stay_prevalence(
    name: str,
    df: pl.DataFrame,
    params: dict[str, object],
    records: list[SuppressionRecord],
    table_blocks: dict[str, dict[str, object]],
    field_audit: dict[str, list[dict[str, str]]],
    all_records: list[SuppressionRecord],
    source_columns: set[str],
    *,
    n_hospitalizations: int,
) -> None:
    """Fit stay prevalence onto ``params`` then record the table block."""
    prev, prec = estimators.fit_stay_prevalence(df, n_hospitalizations)
    params.update(prev)
    _record_table(
        name,
        df,
        params,
        [*records, *prec],
        table_blocks,
        field_audit,
        all_records,
        source_columns,
    )


def _fit_source_prior_tables(
    train_tables: dict[str, pl.LazyFrame],
    tables: dict[str, pl.LazyFrame],
    table_blocks: dict[str, dict[str, object]],
    field_audit: dict[str, list[dict[str, str]]],
    all_records: list[SuppressionRecord],
    *,
    n_hospitalizations: int,
) -> None:
    """Fit source-present tables that were previously prior/spine-only."""
    # code_status (patient-level)
    if "code_status" in train_tables and "hospitalization" in train_tables:
        cs_df = train_tables["code_status"].collect()
        hosp_df = train_tables["hospitalization"].collect()
        params, rec = estimators.fit_code_status_rates(cs_df, hosp_df)
        _record_table(
            "code_status",
            cs_df,
            params,
            rec,
            table_blocks,
            field_audit,
            all_records,
            _source_columns(tables["code_status"]),
        )

    # adt — location marginals + validated arrival / direct-ICU knobs
    if "adt" in train_tables:
        adt_df = train_tables["adt"].collect()
        params, rec = estimators.fit_categorical_marginals(
            adt_df, ("location_category", "location_type", "hospital_type")
        )
        # location_type must be mCIDE-conformant for generation (the source extract uses site
        # labels like ``cvicu_icu`` that are not in the consortium vocabulary).
        try:
            valid_loc = set(loader.categories("adt", "location_type"))
        except Exception:
            valid_loc = set()
        loc_m = params.get("location_type_marginal")
        if isinstance(loc_m, dict) and valid_loc:
            filtered = {k: v for k, v in loc_m.items() if k in valid_loc}
            if filtered:
                total = sum(filtered.values())
                params["location_type_marginal"] = {k: v / total for k, v in filtered.items()}
            else:
                params.pop("location_type_marginal", None)
        arrival, arec = estimators.fit_adt_arrival(adt_df)
        params.update(arrival)
        rec = [*rec, *arec]
        # Mild location enrichment so ward/stepdown/ed appear after arrival when
        # the spine supports them — same enrich_locations flag recalibrate uses.
        if "arrival_location_marginal" in params:
            params["enrich_locations"] = True
        _record_table(
            "adt",
            adt_df,
            params,
            rec,
            table_blocks,
            field_audit,
            all_records,
            _source_columns(tables["adt"]),
        )

    # respiratory_support
    if "respiratory_support" in train_tables:
        rs_df = train_tables["respiratory_support"].collect()
        params, rec = estimators.fit_categorical_marginals(
            rs_df, ("device_category", "mode_category")
        )
        cont, crec = estimators.fit_continuous_marginals(
            rs_df, ("fio2_set", "peep_set", "tidal_volume_set", "resp_rate_set")
        )
        # Drop quantile edges that fall outside consortium bounds (source chart noise).
        for field, edges_key in (
            ("fio2_set", "fio2_set_quantile_bin_edges"),
            ("peep_set", "peep_set_quantile_bin_edges"),
            ("tidal_volume_set", "tidal_volume_set_quantile_bin_edges"),
            ("resp_rate_set", "resp_rate_set_quantile_bin_edges"),
        ):
            edges = cont.get(edges_key)
            if not isinstance(edges, list):
                continue
            try:
                lo, hi = loader.bounds("respiratory_support", field)
            except Exception:
                continue
            clean = [float(e) for e in edges if e is not None and lo <= float(e) <= hi]
            if len(clean) >= 2:
                cont[edges_key] = sorted(set(clean))
            else:
                cont.pop(edges_key, None)
        params.update(cont)
        rec = [*rec, *crec]
        prev, prec = estimators.fit_stay_prevalence_by_category(
            rs_df,
            n_hospitalizations,
            category_col="device_category",
            categories=("IMV", "NIPPV", "High Flow NC"),
        )
        params.update(prev)
        rec = [*rec, *prec]
        # ICU-conditional device prevalences (validated NIV path targets).
        if "adt" in train_tables:
            icu_ids = (
                train_tables["adt"]
                .filter(pl.col("location_category") == _ICU_LOCATION_CATEGORY)
                .select("hospitalization_id")
                .unique()
                .collect()
            )
            n_icu = icu_ids.height
            if n_icu >= 20:
                rs_icu = rs_df.join(icu_ids, on="hospitalization_id", how="inner")
                icu_prev, icu_rec = estimators.fit_stay_prevalence_by_category(
                    rs_icu,
                    n_icu,
                    category_col="device_category",
                    categories=("IMV", "NIPPV", "High Flow NC"),
                )
                params.update({f"icu_{k}": v for k, v in icu_prev.items()})
                rec = [*rec, *icu_rec]
                by_cat = icu_prev.get("stay_prevalence_by_category")
            else:
                by_cat = params.get("stay_prevalence_by_category")
        else:
            by_cat = params.get("stay_prevalence_by_category")
        # Convenience niv block for the gated generator path (validated NIV path).
        if isinstance(by_cat, dict):
            params["niv"] = {
                "nippv_prob": float(by_cat.get("NIPPV", 0.0)),
                "hfnc_prob": float(by_cat.get("High Flow NC", 0.0)),
            }
            params["enrich_devices"] = True
        _record_table(
            "respiratory_support",
            rs_df,
            params,
            rec,
            table_blocks,
            field_audit,
            all_records,
            _source_columns(tables["respiratory_support"]),
        )

    # medication_admin_intermittent
    if "medication_admin_intermittent" in train_tables:
        mai = train_tables["medication_admin_intermittent"].select(
            "hospitalization_id", "med_category"
        ).collect()
        try:
            valid_meds = set(loader.categories("medication_admin_intermittent", "med_category"))
        except Exception:
            valid_meds = set()
        if valid_meds:
            mai_fit = mai.filter(pl.col("med_category").is_in(list(valid_meds)))
            if mai_fit.height < 20:
                mai_fit = mai
        else:
            mai_fit = mai
        params, rec = estimators.fit_top_k_category(mai_fit, "med_category", k=30)
        prev, prec = estimators.fit_stay_prevalence(mai, n_hospitalizations)
        params.update(prev)
        rec = [*rec, *prec]
        _record_table(
            "medication_admin_intermittent",
            mai,
            params,
            rec,
            table_blocks,
            field_audit,
            all_records,
            _source_columns(tables["medication_admin_intermittent"]),
        )

    # microbiology_culture
    if "microbiology_culture" in train_tables:
        cols = [
            c
            for c in (
                "hospitalization_id",
                "fluid_category",
                "method_category",
                "organism_category",
                "organism_group",
            )
            if c in _source_columns(tables["microbiology_culture"])
        ]
        mc = train_tables["microbiology_culture"].select(cols).collect()
        params, rec = estimators.fit_categorical_marginals(
            mc, ("fluid_category", "method_category", "organism_category", "organism_group")
        )
        adt_for_cultures: pl.DataFrame | None = (
            train_tables["adt"].collect() if "adt" in train_tables else None
        )
        rate, rrec = estimators.fit_cultures_per_icu_day(mc, adt_for_cultures)
        params.update(rate)
        rec = [*rec, *rrec]
        prev, prec = estimators.fit_stay_prevalence(mc, n_hospitalizations)
        params.update(prev)
        rec = [*rec, *prec]
        _record_table(
            "microbiology_culture",
            mc,
            params,
            rec,
            table_blocks,
            field_audit,
            all_records,
            _source_columns(tables["microbiology_culture"]),
        )

    # crrt_therapy
    if "crrt_therapy" in train_tables:
        crrt = train_tables["crrt_therapy"].collect()
        params, rec = estimators.fit_categorical_marginals(crrt, ("crrt_mode_category",))
        cont, crec = estimators.fit_continuous_marginals(
            crrt,
            (
                "blood_flow_rate",
                "dialysate_flow_rate",
                "ultrafiltration_out",
                "pre_filter_replacement_fluid_rate",
                "post_filter_replacement_fluid_rate",
            ),
        )
        params.update(cont)
        rec = [*rec, *crec]
        prev, prec = estimators.fit_stay_prevalence(crrt, n_hospitalizations)
        params.update(prev)
        # Validated generator path uses ``crrt_prob`` as P(CRRT | renal flag).
        # Approximate from stay prevalence ÷ renal flag prevalence on the spine.
        if "stay_prevalence" in params and "spine" in table_blocks:
            spine_params = table_blocks["spine"].get("params", {})
            flag_prev: object = (
                spine_params.get("flag_prevalence_by_level", {})
                if isinstance(spine_params, dict)
                else {}
            )
            renal_rates: list[float] = []
            if isinstance(flag_prev, dict):
                for cell in flag_prev.values():
                    if isinstance(cell, dict) and "renal_flag" in cell:
                        renal_rates.append(float(cell["renal_flag"]))
            renal_mean = sum(renal_rates) / len(renal_rates) if renal_rates else 0.0
            if renal_mean > 0:
                stay_prev = params["stay_prevalence"]
                assert isinstance(stay_prev, (int, float))
                params["crrt_prob"] = round(min(1.0, float(stay_prev) / renal_mean), 6)
        rec = [*rec, *prec]
        _record_table(
            "crrt_therapy",
            crrt,
            params,
            rec,
            table_blocks,
            field_audit,
            all_records,
            _source_columns(tables["crrt_therapy"]),
        )

    # ecmo_mcs
    if "ecmo_mcs" in train_tables:
        ecmo = train_tables["ecmo_mcs"].collect()
        params, rec = estimators.fit_categorical_marginals(
            ecmo, ("device_category", "mcs_group")
        )
        cont, crec = estimators.fit_continuous_marginals(
            ecmo, ("flow", "sweep", "fdO2")
        )
        params.update(cont)
        rec = [*rec, *crec]
        prev, prec = estimators.fit_stay_prevalence(ecmo, n_hospitalizations)
        params.update(prev)
        rec = [*rec, *prec]
        _record_table(
            "ecmo_mcs",
            ecmo,
            params,
            rec,
            table_blocks,
            field_audit,
            all_records,
            _source_columns(tables["ecmo_mcs"]),
        )

    # patient_assessments (large — select category only)
    if "patient_assessments" in train_tables:
        pa = train_tables["patient_assessments"].select("assessment_category").collect()
        params, rec = estimators.fit_categorical_marginals(pa, ("assessment_category",))
        _record_table(
            "patient_assessments",
            pa,
            params,
            rec,
            table_blocks,
            field_audit,
            all_records,
            _source_columns(tables["patient_assessments"]),
        )

    # position
    if "position" in train_tables:
        pos = train_tables["position"].collect()
        params, rec = estimators.fit_categorical_marginals(pos, ("position_category",))
        rs_for_prone: pl.DataFrame | None = (
            train_tables["respiratory_support"]
            .select("hospitalization_id", "device_category")
            .collect()
            if "respiratory_support" in train_tables
            else None
        )
        prone, prec = estimators.fit_prone_rates(pos, rs_for_prone)
        params.update(prone)
        rec = [*rec, *prec]
        _record_table(
            "position",
            pos,
            params,
            rec,
            table_blocks,
            field_audit,
            all_records,
            _source_columns(tables["position"]),
        )

    # hospital_diagnosis (top-K codes)
    if "hospital_diagnosis" in train_tables:
        hd = train_tables["hospital_diagnosis"].select(
            "diagnosis_code", "diagnosis_primary"
        ).collect()
        params, rec = estimators.fit_top_k_category(hd, "diagnosis_code", k=40)
        prim, prec = estimators.fit_categorical_marginals(
            hd.with_columns(pl.col("diagnosis_primary").cast(pl.String)),
            ("diagnosis_primary",),
        )
        params.update(prim)
        rec = [*rec, *prec]
        _record_table(
            "hospital_diagnosis",
            hd,
            params,
            rec,
            table_blocks,
            field_audit,
            all_records,
            _source_columns(tables["hospital_diagnosis"]),
        )

    # patient_procedures — intersect with vendored CPT list when possible
    if "patient_procedures" in train_tables:
        pp = (
            train_tables["patient_procedures"]
            .select("hospitalization_id", "procedure_code")
            .collect()
        )
        try:
            vendored = {row["procedure_code"] for row in loader.code_list("patient_procedures")}
        except Exception:
            vendored = set()
        if vendored:
            pp_filtered = pp.filter(pl.col("procedure_code").is_in(list(vendored)))
            pp_fit = pp_filtered if pp_filtered.height >= 20 else pp
        else:
            pp_fit = pp
        params, rec = estimators.fit_top_k_category(pp_fit, "procedure_code", k=40)
        prev, prec = estimators.fit_stay_prevalence(pp, n_hospitalizations)
        params.update(prev)
        rec = [*rec, *prec]
        _record_table(
            "patient_procedures",
            pp,
            params,
            rec,
            table_blocks,
            field_audit,
            all_records,
            _source_columns(tables["patient_procedures"]),
        )

    # --- previously dashboard-prior tables (hybrid: fit when source present) ---
    if "invasive_hemodynamics" in train_tables:
        hemo = train_tables["invasive_hemodynamics"].collect()
        params, rec = estimators.fit_categorical_marginals(hemo, ("measure_category",))
        cont, crec = estimators.fit_continuous_marginals(hemo, ("measure_value",))
        params.update(cont)
        rec = [*rec, *crec]
        # Per-measure value edges when volume allows.
        if "measure_category" in hemo.columns and "measure_value" in hemo.columns:
            for cat in hemo["measure_category"].drop_nulls().unique().to_list():
                sub = hemo.filter(pl.col("measure_category") == cat)
                edges_params, _ = estimators.fit_continuous_marginals(sub, ("measure_value",))
                edges = edges_params.get("measure_value_quantile_bin_edges")
                if isinstance(edges, list) and len(edges) >= 2:
                    params[f"{cat}_quantile_bin_edges"] = list(edges)
        _record_with_stay_prevalence(
            "invasive_hemodynamics",
            hemo,
            params,
            rec,
            table_blocks,
            field_audit,
            all_records,
            _source_columns(tables["invasive_hemodynamics"]),
            n_hospitalizations=n_hospitalizations,
        )

    if "transfusion" in train_tables:
        tx = train_tables["transfusion"].collect()
        params, rec = estimators.fit_top_k_category(tx, "component_name", k=20)
        cont, crec = estimators.fit_continuous_marginals(tx, ("volume_transfused",))
        params.update(cont)
        rec = [*rec, *crec]
        prev, prec = estimators.fit_stay_prevalence(tx, n_hospitalizations)
        params.update(prev)
        stay_prev = params.get("stay_prevalence")
        if isinstance(stay_prev, (int, float)) and float(stay_prev) > 0:
            n_pos = tx["hospitalization_id"].n_unique()
            params["events_per_positive_stay"] = round(tx.height / max(1, n_pos), 4)
        rec = [*rec, *prec]
        _record_table(
            "transfusion",
            tx,
            params,
            rec,
            table_blocks,
            field_audit,
            all_records,
            _source_columns(tables["transfusion"]),
        )

    if "key_icu_orders" in train_tables:
        orders = train_tables["key_icu_orders"].collect()
        params, rec = estimators.fit_categorical_marginals(orders, ("order_category",))
        _record_with_stay_prevalence(
            "key_icu_orders",
            orders,
            params,
            rec,
            table_blocks,
            field_audit,
            all_records,
            _source_columns(tables["key_icu_orders"]),
            n_hospitalizations=n_hospitalizations,
        )

    if "therapy_details" in train_tables:
        td = train_tables["therapy_details"].collect()
        params, rec = estimators.fit_categorical_marginals(td, ("therapy_element_category",))
        if "therapy_element_value" in td.columns and "therapy_element_category" in td.columns:
            value_by_cat: dict[str, str] = {}
            for cat in td["therapy_element_category"].drop_nulls().unique().to_list():
                mode = (
                    td.filter(pl.col("therapy_element_category") == cat)["therapy_element_value"]
                    .drop_nulls()
                    .mode()
                )
                if mode.len():
                    value_by_cat[str(cat)] = str(mode[0])
            if value_by_cat:
                params["therapy_element_value_by_category"] = value_by_cat
        _record_with_stay_prevalence(
            "therapy_details",
            td,
            params,
            rec,
            table_blocks,
            field_audit,
            all_records,
            _source_columns(tables["therapy_details"]),
            n_hospitalizations=n_hospitalizations,
        )

    if "provider" in train_tables:
        prov = train_tables["provider"].collect()
        params, rec = estimators.fit_categorical_marginals(prov, ("provider_role_category",))
        roles = (
            prov.group_by("hospitalization_id")
            .agg(pl.len().alias("n"))
            .select(pl.col("n").mean())
            .item()
        )
        if roles is not None:
            params["roles_per_stay"] = round(float(roles), 3)
        _record_with_stay_prevalence(
            "provider",
            prov,
            params,
            rec,
            table_blocks,
            field_audit,
            all_records,
            _source_columns(tables["provider"]),
            n_hospitalizations=n_hospitalizations,
        )

    if "microbiology_nonculture" in train_tables:
        mnc = train_tables["microbiology_nonculture"].collect()
        params, rec = estimators.fit_categorical_marginals(
            mnc, ("fluid_category", "organism_category", "result_category")
        )
        prev, prec = estimators.fit_stay_prevalence(mnc, n_hospitalizations)
        params.update(prev)
        stay_prev = params.get("stay_prevalence")
        n_pos = mnc["hospitalization_id"].n_unique()
        if n_pos >= 1:
            # Intensity among positive stays — not interchangeable with stay prevalence.
            params["panels_per_stay"] = round(mnc.height / n_pos, 4)
        elif isinstance(stay_prev, (int, float)):
            params["panels_per_stay"] = float(stay_prev)
        rec = [*rec, *prec]
        _record_table(
            "microbiology_nonculture",
            mnc,
            params,
            rec,
            table_blocks,
            field_audit,
            all_records,
            _source_columns(tables["microbiology_nonculture"]),
        )

    if "intake_output" in train_tables:
        io = train_tables["intake_output"].collect()
        # Fit intake fluid names only — urine is the hardcoded output fluid.
        if "in_out_flag" in io.columns:
            intake_only = io.filter(pl.col("in_out_flag") == 1)
            params, rec = estimators.fit_top_k_category(
                intake_only if intake_only.height else io, "fluid_name", k=30
            )
        else:
            params, rec = estimators.fit_top_k_category(io, "fluid_name", k=30)
        cont, crec = estimators.fit_continuous_marginals(io, ("amount",))
        params.update(cont)
        rec = [*rec, *crec]
        by_flag: dict[str, list[float]] = {}
        if "in_out_flag" in io.columns:
            for flag in io["in_out_flag"].drop_nulls().unique().to_list():
                sub = io.filter(pl.col("in_out_flag") == flag)
                edges_params, _ = estimators.fit_continuous_marginals(sub, ("amount",))
                edges = edges_params.get("amount_quantile_bin_edges")
                if isinstance(edges, list) and len(edges) >= 2:
                    by_flag[str(flag)] = list(edges)
        if by_flag:
            params["amount_quantile_bin_edges_by_in_out_flag"] = by_flag
        params["chart_interval_hours"] = 1.0
        _record_table(
            "intake_output",
            io,
            params,
            rec,
            table_blocks,
            field_audit,
            all_records,
            _source_columns(tables["intake_output"]),
        )

    if "clinical_trial" in train_tables:
        ct = train_tables["clinical_trial"].collect()
        # Rates only — never persist real NCT / trial name strings (PHI / attribution).
        # Fit prevalence among eligible (ventilated / high-acuity) stays when hosp
        # peak is available; otherwise unconditional stay prevalence.
        params, rec = estimators.fit_stay_prevalence(ct, n_hospitalizations)
        # Approximate eligibility via IMV when hosp peak is not on the trial table.
        if (
            "support_level" not in ct.columns
            and "respiratory_support" in train_tables
        ):
            imv_ids = (
                train_tables["respiratory_support"]
                .filter(pl.col("device_category") == "IMV")
                .select("hospitalization_id")
                .unique()
                .collect()
            )
            n_elig = imv_ids.height
            if n_elig >= 20:
                n_enrolled = (
                    ct.select("hospitalization_id")
                    .unique()
                    .join(imv_ids, on="hospitalization_id", how="inner")
                    .height
                )
                params["eligible_conditional_prevalence"] = round(n_enrolled / n_elig, 6)
        if "withdrawal_dttm" in ct.columns:
            n = ct.height
            withdrawn = ct.filter(pl.col("withdrawal_dttm").is_not_null()).height
            if n >= 20:
                params["withdrawal_prob"] = round(withdrawn / n, 4)
        _record_table(
            "clinical_trial",
            ct,
            params,
            rec,
            table_blocks,
            field_audit,
            all_records,
            _source_columns(tables["clinical_trial"]),
        )

    if "place_based_index" in train_tables:
        pbi = train_tables["place_based_index"].collect()
        params, rec = estimators.fit_categorical_marginals(pbi, ("index_name",))
        by_name: dict[str, list[float]] = {}
        if "index_name" in pbi.columns and "index_value" in pbi.columns:
            for name in pbi["index_name"].drop_nulls().unique().to_list():
                sub = pbi.filter(pl.col("index_name") == name)
                edges_params, _ = estimators.fit_continuous_marginals(sub, ("index_value",))
                edges = edges_params.get("index_value_quantile_bin_edges")
                if isinstance(edges, list) and len(edges) >= 2:
                    by_name[str(name)] = list(edges)
        if by_name:
            params["index_value_quantile_bin_edges_by_name"] = by_name
        _record_table(
            "place_based_index",
            pbi,
            params,
            rec,
            table_blocks,
            field_audit,
            all_records,
            _source_columns(tables["place_based_index"]),
        )


# --------------------------------------------------------------------------- #
# Suppression-audit roll-up
# --------------------------------------------------------------------------- #
def _rollup(records: list[SuppressionRecord]) -> dict[str, object]:
    """Summarize the suppression audit honestly.

    ``cell_gate.suppress`` emits a record *only* for a cell that fell below the
    n>=20 floor — cells that pass leave no trace — so this counts suppression
    events by disposition, not the total cells considered. A clean fit therefore
    reports all-zero counts, meaning "no cell fell below the floor" (not "the
    gate never ran"). The ``note`` states that so the artifact can't be
    misread.
    """
    by_kind: dict[str, int] = {}
    for r in records:
        by_kind[r.fallback_kind] = by_kind.get(r.fallback_kind, 0) + 1
    return {
        "cells_below_min_n": len(records),
        "dropped_no_fallback": by_kind.get("none", 0),
        "fell_back_to_prior": by_kind.get("prior", 0),
        "fell_back_to_coarser_aggregate": by_kind.get("coarser_aggregate", 0),
        "note": "counts only cells below the n>=20 floor; passing cells emit no record",
    }


# --------------------------------------------------------------------------- #
# Driver
# --------------------------------------------------------------------------- #
def run_fit(
    real_dir: str | Path,
    out_dir: str | Path,
    *,
    seed: int = 20260723,
    holdout_fraction: float = 0.2,
    dataset_id: str = "credentialed-clif",
    config: SpineStateConfig | None = None,
) -> ParamPack:
    """Fit a real CLIF dataset into an aggregate parameter pack and write it."""
    real_dir = Path(real_dir)
    config = config or SpineStateConfig()
    tables = _load_tables(real_dir)
    if "patient" not in tables or "hospitalization" not in tables:
        raise ValueError("real-dir must contain at least patient and hospitalization tables")

    # --- seeded, patient-disjoint training partition -----------------------
    patient_ids = tables["patient"].select("patient_id").collect().to_series().to_list()
    train_patients, split_spec = _split_patients(
        [str(p) for p in patient_ids], seed, holdout_fraction
    )
    train_hosp = (
        tables["hospitalization"]
        .filter(pl.col("patient_id").cast(pl.String).is_in(list(train_patients)))
        .select("hospitalization_id")
        .collect()
        .to_series()
        .to_list()
    )
    train_hosp_set = list(train_hosp)

    def restrict(lf: pl.LazyFrame, key: str) -> pl.LazyFrame:
        return lf.filter(pl.col(key).is_in(train_hosp_set))

    # Training-partition views (patient-keyed vs hospitalization-keyed).
    train_tables: dict[str, pl.LazyFrame] = {}
    for name, lf in tables.items():
        cols = set(lf.collect_schema().names())
        if "hospitalization_id" in cols:
            train_tables[name] = restrict(lf, "hospitalization_id")
        elif "patient_id" in cols:
            train_tables[name] = lf.filter(
                pl.col("patient_id").cast(pl.String).is_in(list(train_patients))
            )
        else:
            train_tables[name] = lf

    admits = spine_state._admissions(train_tables["hospitalization"])

    table_blocks: dict[str, dict[str, object]] = {}
    all_records: list[SuppressionRecord] = []
    field_audit: dict[str, list[dict[str, str]]] = {}

    # --- patient marginals -------------------------------------------------
    patient_df = train_tables["patient"].collect()
    p_params, p_rec = estimators.fit_categorical_marginals(patient_df, _PATIENT_CATEGORICALS)
    all_records.extend(p_rec)
    table_blocks["patient"] = {
        "n_records": patient_df.height,
        "fitted": True,
        "params": p_params,
    }
    field_audit["patient"] = _field_sources(
        "patient", set(patient_df.columns), _MODELED_COLUMNS["patient"]
    )

    # --- hospitalization marginals ----------------------------------------
    hosp_df = train_tables["hospitalization"].collect()
    h_params, h_rec = estimators.fit_categorical_marginals(hosp_df, _HOSPITALIZATION_CATEGORICALS)
    all_records.extend(h_rec)
    age_params, age_rec = estimators.fit_age_quantiles(hosp_df)
    all_records.extend(age_rec)
    h_params.update(age_params)
    table_blocks["hospitalization"] = {
        "n_records": hosp_df.height,
        "fitted": True,
        "params": h_params,
    }
    field_audit["hospitalization"] = _field_sources(
        "hospitalization", set(hosp_df.columns), _MODELED_COLUMNS["hospitalization"]
    )

    # --- semi-Markov spine: transitions, sojourns, outcome, flags ---------
    timeline = spine_state.derive_state_timeline(train_tables, config).collect()
    outcomes = spine_state.outcome_by_hospitalization(train_tables["hospitalization"]).collect()
    t_params, t_rec = estimators.fit_transitions(timeline)
    s_params, s_rec = estimators.fit_sojourns(timeline, grid_step_hours=config.grid_step_hours)
    o_params, o_rec = estimators.fit_outcome_rates(timeline, outcomes)
    f_params, f_rec = estimators.fit_flag_prevalence(timeline)
    all_records.extend(t_rec)
    all_records.extend(s_rec)
    all_records.extend(o_rec)
    all_records.extend(f_rec)
    table_blocks["spine"] = {
        "n_records": timeline["hospitalization_id"].n_unique(),
        "fitted": True,
        "params": {
            **t_params,
            **s_params,
            **o_params,
            **f_params,
            "state_model": config.as_manifest(),
            # Validated trajectory defaults (same knobs recalibrate_to_network_median
            # sets). Empirical reference spine rates are preserved; these only enable the
            # terminal-decline path the generators already honor.
            "terminal_deterioration_hours": 24.0,
        },
    }
    # Coupled admission route (validated full-hospital / ADT front-door method):
    # one draw per stay drives hospitalization admission_type and ADT arrival.
    route_params, route_rec = estimators.fit_admission_route_marginal(hosp_df)
    all_records.extend(route_rec)
    if route_params:
        spine_params = table_blocks["spine"]["params"]
        assert isinstance(spine_params, dict)
        spine_params.update(route_params)

    # --- per-state AR1 physiology -----------------------------------------
    if "vitals" in train_tables:
        vitals_grid = _grid_value_table(
            train_tables["vitals"],
            admits,
            dttm_col=_GRID_DTTM["vitals"],
            category_col="vital_category",
            value_col="vital_value",
            config=config,
        )
        ar1_params, ar1_rec = estimators.fit_ar1_by_state(vitals_grid, timeline, vitals=_AR1_VITALS)
        all_records.extend(ar1_rec)
        table_blocks["vitals"] = {
            "n_records": vitals_grid.height,
            "fitted": True,
            "params": ar1_params,
        }
        field_audit["vitals"] = _field_sources(
            "vitals", _source_columns(tables["vitals"]), _MODELED_COLUMNS["vitals"]
        )

    # --- lab co-measurement copula ----------------------------------------
    if "labs" in train_tables:
        # Prefer the result time (real CLIF), but fall back to the order time when the
        # result timestamp is absent — synthetic labs carry only ``lab_order_dttm``, so
        # this lets the fit run on a synthetic dataset (fit-on-synthetic base pack).
        lab_cols = _source_columns(tables["labs"])
        labs_dttm = _GRID_DTTM["labs"] if _GRID_DTTM["labs"] in lab_cols else "lab_order_dttm"
        labs_grid = _grid_value_table(
            train_tables["labs"],
            admits,
            dttm_col=labs_dttm,
            category_col="lab_category",
            value_col="lab_value_numeric",
            config=config,
        )
        n_hosp = len(train_hosp_set)
        # ICU-exposed cohort for conditioning lab presence: the population the
        # synthetic dataset represents (every generated stay is an ICU encounter).
        # Prefer the clinically-defined ICU cohort from ADT (location_category
        # == "icu"); the latent support-level cohort is a narrower, sicker subset
        # that inflates per-stay presence for intermittent labs (lactate, arterial
        # blood gases) several points above the true ICU rate. Fall back to the
        # support-level timeline only when ADT location data is unavailable.
        icu_hosp = _icu_cohort(train_tables.get("adt"))
        if not icu_hosp:
            icu_hosp = set(
                timeline.filter(pl.col("support_level") >= _ICU_MIN_SUPPORT_LEVEL)
                .select("hospitalization_id")
                .unique()
                .to_series()
                .to_list()
            )
        lab_params, lab_rec = estimators.fit_lab_copula(
            labs_grid, n_hospitalizations=n_hosp, icu_hospitalizations=icu_hosp
        )
        all_records.extend(lab_rec)
        table_blocks["labs"] = {
            "n_records": labs_grid.height,
            "fitted": True,
            "params": lab_params,
        }
        field_audit["labs"] = _field_sources(
            "labs", _source_columns(tables["labs"]), _MODELED_COLUMNS["labs"]
        )

    # --- infusion hazards --------------------------------------------------
    if "medication_admin_continuous" in train_tables:
        mac_grid = _grid_value_table(
            train_tables["medication_admin_continuous"],
            admits,
            dttm_col=_GRID_DTTM["medication_admin_continuous"],
            category_col="med_category",
            value_col="med_dose",
            config=config,
        )
        haz_params, haz_rec = estimators.fit_infusion_hazards(mac_grid)
        all_records.extend(haz_rec)
        table_blocks["medication_admin_continuous"] = {
            "n_records": mac_grid.height,
            "fitted": True,
            "params": haz_params,
        }
        field_audit["medication_admin_continuous"] = _field_sources(
            "medication_admin_continuous",
            _source_columns(tables["medication_admin_continuous"]),
            _MODELED_COLUMNS["medication_admin_continuous"],
        )

    # --- source-present prior tables (all-28 realism pack) ------------------
    n_hosp = len(train_hosp_set)
    _fit_source_prior_tables(
        train_tables,
        tables,
        table_blocks,
        field_audit,
        all_records,
        n_hospitalizations=n_hosp,
    )

    # --- assemble manifest + pack -----------------------------------------
    ref = loader.provenance()
    manifest: dict[str, object] = {
        "pack_version": "1.0",
        "clif_version": ref["clif_version"],
        "fit_source": {
            "dataset_id": dataset_id,
            "commit": "unknown",
        },
        "reference_source": {
            "source_repo": ref.get("source_repo"),
            "source_commit": ref.get("source_commit"),
            "retrieved_at": ref.get("retrieved_at"),
        },
        "split": split_spec,
        "field_sources": field_audit,
        "tables": {name: {"fitted": block["fitted"]} for name, block in table_blocks.items()},
        "suppression_audit": {"overall": _rollup(all_records)},
        "citation": DEFAULT_CITATION,
    }

    pack = ParamPack(manifest=manifest, tables=table_blocks)
    findings = scan_for_leakage(pack)
    if findings:
        rendered = "\n".join(f"  - {f.describe()}" for f in findings)
        raise RuntimeError(f"refusing to write pack — leakage scan found:\n{rendered}")
    pack.write(out_dir)
    return pack


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description="Fit a real CLIF dataset into a parameter pack.")
    parser.add_argument("--real-dir", required=True, help="directory of real CLIF tables")
    parser.add_argument("--out", required=True, help="output parameter-pack directory")
    parser.add_argument("--seed", type=int, default=20260723)
    parser.add_argument("--holdout-fraction", type=float, default=0.2)
    parser.add_argument("--dataset-id", default="credentialed-clif")
    parser.add_argument("--grid-step-hours", type=float, default=1.0)
    args = parser.parse_args(argv)

    config = SpineStateConfig(grid_step_hours=args.grid_step_hours)
    pack = run_fit(
        args.real_dir,
        args.out,
        seed=args.seed,
        holdout_fraction=args.holdout_fraction,
        dataset_id=args.dataset_id,
        config=config,
    )
    n_tables = len(pack.tables)
    print(f"Wrote parameter pack with {n_tables} table block(s) to {args.out}")


if __name__ == "__main__":
    main()
