"""Generate committed per-table pandera schema modules from the 2.1.0 dictionary (U3).

Reads the vendored data dictionary + mCIDE/outlier reference (U2) and emits one
``src/clifforge/schemas/<table>.py`` per CLIF table, each exposing a ``SCHEMA``
built from explicit, inspectable ``base.*`` factory calls. The emitted decision
per column mirrors ``clifforge.schemas.base.build_column`` exactly, so the
committed files and the runtime builder never diverge.

Generated files are meant to be committed and then *refined* by each table's
implementation unit (append clinical-coupling checks below the generated SCHEMA —
e.g. the respiratory_support device/mode matrix, R10). The column list itself is
regenerated, not hand-edited::

    uv run python scripts/gen_schemas.py
"""

from __future__ import annotations

import subprocess
from pathlib import Path

from clifforge.reference import loader
from clifforge.schemas import base

SCHEMAS_DIR = Path(__file__).resolve().parent.parent / "src" / "clifforge" / "schemas"


def _column_expr(table: str, name: str, dtype: str) -> str:
    """Return the ``base.*`` call string for one column — mirrors base.build_column."""
    dt = dtype.upper()

    field = base._category_field(table, name)
    if field is not None:
        return f'base.category("{table}", "{field}")'

    if dt == "DATETIME":
        return "base.utc_datetime()"

    if dt == "DATE":
        return "base.date()"

    if name in base.NUMERIC_ID_COLUMNS:
        if name in base.REQUIRED_ID_COLUMNS:
            return "base.numeric_id_column()"
        return "base.numeric_id_column(required=False, nullable=True)"

    if name.endswith("_id"):
        return "base.id_column()"

    if dt in base._FLOAT_DTYPES:
        try:
            loader.bounds(table, name)
        except loader.ReferenceDataError:
            return "base.plain_float()"
        return f'base.bounded_float("{table}", "{name}")'

    if dt in base._INT_DTYPES:
        return "base.integer()"

    if dt in base._BOOL_DTYPES:
        return "base.boolean()"

    return "base.string()"


def _render(table: str) -> str:
    maturity = loader.table_maturity(table) or "untiered"
    columns = loader.table_columns(table)
    lines = [
        '"""AUTO-GENERATED by scripts/gen_schemas.py from the CLIF 2.1.0 data dictionary.',
        "",
        "Do not hand-edit the generated column list; regenerate with",
        "``uv run python scripts/gen_schemas.py``. A table unit MAY append clinical-coupling",
        "refinements below SCHEMA via .update_column()/.add_columns() (see U3 / R15).",
        "",
        f"Table: {table} ({maturity})",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "import pandera.polars as pa",
        "",
        "from clifforge.schemas import base",
        "",
        "SCHEMA: pa.DataFrameSchema = pa.DataFrameSchema(",
        "    {",
    ]
    for col in columns:
        lines.append(f'        "{col["name"]}": {_column_expr(table, col["name"], col["dtype"])},')
    lines += [
        "    },",
        "    strict=False,",
        "    coerce=False,",
        f'    name="{table}",',
        ")",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    SCHEMAS_DIR.mkdir(parents=True, exist_ok=True)
    generated = []
    for table in loader.dictionary_tables():
        # Sanity: building at runtime must succeed before we emit the file.
        base.schema_from_dictionary(table)
        path = SCHEMAS_DIR / f"{table}.py"
        path.write_text(_render(table), encoding="utf-8")
        generated.append(table)
    # Ruff-format the emitted files so long bounded-float/category call lines wrap
    # to the repo's line-length; regeneration then stays lint-clean (E501).
    subprocess.run(["ruff", "format", str(SCHEMAS_DIR)], check=True)
    subprocess.run(["ruff", "check", "--fix", "--quiet", str(SCHEMAS_DIR)], check=True)
    print(f"Generated {len(generated)} schema modules in {SCHEMAS_DIR}:")
    for t in generated:
        print(f"  schemas/{t}.py")


if __name__ == "__main__":
    main()
